# Generated by Django 4.1.4 on 2022-12-25 13:58

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('jobType', models.CharField(choices=[('正社員', 'Permanent'), ('契約社員', 'Temporary'), ('インターン', 'Intership'), ('その他', 'Others')], default='正社員', max_length=10)),
                ('education', models.CharField(choices=[('高校卒', 'Highscools'), ('専門卒', 'Technicalschools'), ('短大卒', 'Juniorcolleges'), ('大卒', 'Bachelors'), ('修士', 'Masters'), ('博士', 'Phd'), ('その他', 'Others')], default='大卒', max_length=10)),
                ('experience', models.CharField(choices=[('未経験', 'No Experience'), ('1年', 'One Year'), ('2年', 'Two Year'), ('3年以上', 'Three Year Plus')], default='未経験', max_length=10)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(1000000)])),
                ('positions', models.IntegerField(default=1)),
                ('company', models.CharField(max_length=100, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('lastDate', models.DateTimeField(default=datetime.datetime(2023, 1, 4, 13, 58, 49, 486115))),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
