# Generated by Django 4.1.4 on 2022-12-25 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('ビジネス', 'Business'), ('IT', 'It'), ('金融', 'Banking'), ('教育', 'Education'), ('通信', 'Telecommunication'), ('その他', 'Others')], default='ビジネス', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='lastDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 14, 7, 19, 652145)),
        ),
    ]
